### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava-init#5]
See https://github.com/sindresorhus/xo-init/commit/89fc57105cde289c30299ac8796aa4eb4dc84598 and https://github.com/sindresorhus/xo-init/commit/0638726fe8452775a64cdf94202c2a5550eb10a0 for how to implement it.

**Comment by vadimdemedes** [comment]
Looking at these commits, it seems to be implemented. What's missing?

**Comment by sindresorhus** [comment]
@vadimdemedes Those commits are from `xo-init`, this is `ava-init`.

**Comment by forresst** [comment]
@sindresorhus 

Maybe drop support for Node.js 0.10 and 0.12 as avajs/ava@8530fcdf304eed0e23b7915633f3a15fd1a4e65a ?

This will also make it possible to apply the TODO https://github.com/avajs/ava-init/blob/master/index.js#L53 ?

**Comment by sindresorhus** [comment]
@forresst Done: https://github.com/avajs/ava-init/commit/1d7d73b3022f34e1b749cc2285422a4dff1870d3
